### ISSUE TITLE
zoom should have more options

### ISSUE THREAD

**Issue by joe438** [Nekomajin42/Site-Settings-Sidebar#1]
zoom is nice and I like how I can set the zoom to 123, but it would be nice to set the up/down arrows to increase the value by 1 or 10 or 50.  Currently it only can zoom up to 200.  In some cases it is better to be able to zoom further than that for testing purposes, etc.

**Comment by Nekomajin42** [comment]
Thanks for the feedback. I will look after it in the next few days.

**Comment by Nekomajin42** [comment]
I've changed to max zoom value to 500% which is the biggest value recognized by the browser. I've also added an option to change the step of the zoom input.
I hope it will be available before the weekend.

**Comment by joe438** [comment]
Nice :)  I'm looking forward to trying it out.

**Comment by joe438** [comment]
My apologies about the late reply.  I like the new changes to the zoom.  I wish Opera zoom behaved this way.

**Comment by Nekomajin42** [comment]
I'm working on another extension related only to zoom. It will be available in the next few weeks.
